name: "Sniffs"

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"

jobs:
    phpcs-sniffs:
        name: "Display PHPCS rules"
        runs-on: "ubuntu-24.04"
        steps:
        -
            name: "Check out repository"
            uses: "actions/checkout@v4"
        -
            name: "Set up PHP"
            uses: "shivammathur/setup-php@v2"
            with:
                php-version: "8.0"
        -
            name: "Install dependencies"
            uses: "ramsey/composer-install@v3"
            with:
                dependency-versions: "highest"
        -
            name: "List included rules"
            run: |
                vendor/bin/phpcs -e --standard=PSR12NeutronRuleset
