name: "XML"

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"

jobs:
    validate:
        name: "Validate XML"
        runs-on: "ubuntu-22.04"
        steps:
        -
            name: "Check out repository"
            uses: "actions/checkout@v3"
        -
            name: "Set up PHP"
            uses: "shivammathur/setup-php@v2"
            with:
                php-version: "8.0"
        -
            name: "Install dependencies"
            uses: "ramsey/composer-install@v2"
            with:
                dependency-versions: "highest"
                composer-options: "--no-plugins --no-scripts"
        -
            name: "Validate XML files"
            uses: "./.github/actions/xml-validate"
            with:
                xml_phpcs_schema: "vendor/squizlabs/php_codesniffer/phpcs.xsd"
                xml_ruleset: "PSR12NeutronRuleset/ruleset.xml"
